#!/usr/bin/env bash
# configure.sh — interactive generator for cluster.yaml
# Asks how many load balancers / control planes / workers you want,
# the subnet, and the per-role IP ranges, then writes cluster.yaml
# which the Vagrantfile builds from.
set -euo pipefail
c(){ printf '\033[%sm' "$1"; }
BLU=$(c '1;36'); GRN=$(c '1;32'); YLW=$(c '0;33'); RED=$(c '1;31'); BLD=$(c '1'); RST=$(c '0')
info(){ printf '   %s\n' "$*"; }
ok(){ printf '   %s\xe2\x9c\x93 %s%s\n' "$GRN" "$*" "$RST"; }
ask(){ local p="$1" d="${2:-}" a; if [ -n "$d" ]; then printf '%s [%s]: ' "$p" "$d" >/dev/tty; else printf '%s: ' "$p" >/dev/tty; fi; IFS= read -r a </dev/tty || true; printf '%s' "${a:-$d}"; }

printf '%s\n' "${BLU}${BLD}Kubernetes HA Cluster — interactive configurator${RST}"
echo "Answer a few questions; this writes cluster.yaml for Vagrant. Press Enter to accept [defaults]."
echo

SUBNET=$(ask "Subnet — first three octets (host-only /24)" "192.168.56")

while :; do NLB=$(ask "How many LOAD BALANCERS? (1-3)" "2"); [[ "$NLB" =~ ^[1-3]$ ]] && break; info "${YLW}Please enter 1, 2 or 3.${RST}"; done
while :; do NCP=$(ask "How many CONTROL PLANES? (odd: 1,3,5,7)" "3"); [[ "$NCP" =~ ^(1|3|5|7)$ ]] && break; info "${YLW}Control planes must be odd (1,3,5,7) so etcd keeps quorum.${RST}"; done
while :; do NWK=$(ask "How many WORKER nodes? (0-9)" "2"); [[ "$NWK" =~ ^[0-9]$ ]] && break; info "${YLW}Please enter 0-9.${RST}"; done

VIP_H=$(ask "VIP host octet (the floating API address)" "10")
LB_S=$(ask "Load-balancer start octet" "5")
CP_S=$(ask "Control-plane start octet" "11")
WK_S=$(ask "Worker start octet" "21")

# --- pick a base box from a footprint-annotated menu ---
{
  printf '\n%sChoose a base box%s (smaller = more VMs fit on your laptop):\n' "$BLD" "$RST"
  printf '  1) bento/debian-12      Debian 12 minimal   ~120 MB idle, ~2 GB disk   [recommended]\n'
  printf '  2) bento/ubuntu-24.04   Ubuntu 24.04 LTS    ~200 MB idle  (familiar)\n'
  printf '  3) bento/ubuntu-22.04   Ubuntu 22.04 LTS    ~200 MB idle  (matches the courses)\n'
  printf '  4) generic/debian12     Debian 12 (roboxes) fallback if bento is unavailable\n'
} >/dev/tty
BCHOICE=$(ask "Box choice (1-4, or type any box name)" "1")
case "$BCHOICE" in
  1) BOX="bento/debian-12" ;;
  2) BOX="bento/ubuntu-24.04" ;;
  3) BOX="bento/ubuntu-22.04" ;;
  4) BOX="generic/debian12" ;;
  *) BOX="$BCHOICE" ;;
esac
info "Box: ${GRN}$BOX${RST}"
K8S=$(ask "Kubernetes version (minor)" "v1.36")
PODCIDR=$(ask "Pod network CIDR (must NOT overlap your subnet)" "10.244.0.0/16")
CALICO=$(ask "Calico version" "v3.29.1")

echo
info "Per-VM memory in MB — all VMs run at once, so keep your host's RAM in mind:"
LBMEM=$(ask "  Load-balancer RAM" "512")
CPMEM=$(ask "  Control-plane RAM (>=1800 recommended)" "2048")
WKMEM=$(ask "  Worker RAM" "1536")

OUT="$(dirname "$0")/cluster.yaml"
{
  echo "# Generated by configure.sh — edit by re-running it, or by hand."
  echo "subnet: \"$SUBNET\""
  echo "vip: \"$SUBNET.$VIP_H\""
  echo "box: \"$BOX\""
  echo "k8s_version: \"$K8S\""
  echo "pod_cidr: \"$PODCIDR\""
  echo "calico_version: \"$CALICO\""
  echo "resources:"
  echo "  lb: { memory: $LBMEM, cpus: 1 }"
  echo "  cp: { memory: $CPMEM, cpus: 2 }"
  echo "  wk: { memory: $WKMEM, cpus: 1 }"
  echo "load_balancers:"
  for i in $(seq 1 "$NLB"); do echo "  - { name: k8s-lb$i, ip: $SUBNET.$((LB_S + i - 1)) }"; done
  echo "control_planes:"
  for i in $(seq 1 "$NCP"); do echo "  - { name: k8s-cp$i, ip: $SUBNET.$((CP_S + i - 1)) }"; done
  echo "workers:"
  if [ "$NWK" -gt 0 ]; then for i in $(seq 1 "$NWK"); do echo "  - { name: k8s-w$i, ip: $SUBNET.$((WK_S + i - 1)) }"; done; else echo "  []"; fi
} > "$OUT"

echo
ok "Wrote $OUT"
echo
printf '%s%s\n' "$BLD" "Planned cluster:${RST}"
printf '   %-10s %-26s %s\n' "ROLE" "HOSTNAME" "IP"
printf '   %-10s %-26s %s\n' "VIP" "k8s-vip" "$SUBNET.$VIP_H"
for i in $(seq 1 "$NLB"); do printf '   %-10s %-26s %s\n' "loadbal"  "k8s-lb$i" "$SUBNET.$((LB_S + i - 1))"; done
for i in $(seq 1 "$NCP"); do printf '   %-10s %-26s %s\n' "control"  "k8s-cp$i" "$SUBNET.$((CP_S + i - 1))"; done
if [ "$NWK" -gt 0 ]; then for i in $(seq 1 "$NWK"); do printf '   %-10s %-26s %s\n' "worker" "k8s-w$i" "$SUBNET.$((WK_S + i - 1))"; done; fi
TOTMEM=$(( NLB*LBMEM + NCP*CPMEM + NWK*WKMEM ))
echo
info "Estimated VM memory: ${BLD}${TOTMEM} MB${RST}  (${NLB}x${LBMEM} + ${NCP}x${CPMEM} + ${NWK}x${WKMEM}). Leave a few GB free for your host."
[ "$TOTMEM" -gt 12288 ] && info "${YLW}That's heavy — consider fewer nodes or less RAM per node.${RST}"
echo
echo "Next:  ${GRN}vagrant up${RST}   then follow README.md to run the setup scripts on each node."
[ "$NLB" -lt 2 ] && info "${YLW}Note: with 1 load balancer there is no VIP failover (single point of failure). Use 2+ for true HA.${RST}"
exit 0
